application: map-it-out
version: 1
runtime: python
api_version: 1

handlers:
 


- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /static
  static_dir: static


- url: /hellomap
  static_dir: hellomap.html
               
- url: .*
  script: main.py
                     

